### PR TITLE
[Deps] update 'glob'

### PR DESCRIPTION
**Pull request by lloydjatkinson**
This PR upgrades the `glob` dependency. All tests pass with 8.x.x, and fail on any newer versions.

### CODE REVIEW

**Comment by bunglegrind** [comment]
https://github.com/tape-testing/tape/issues/611#issuecomment-2316302671

**Comment by ljharb** [comment]
Duplicate of #611; and as you can see, tests do not pass.

**Comment by lloydjatkinson** [comment]
OK, will migrate to vitest.

**Comment by lloydjatkinson** [comment]
```shell
"glob": "^7.2.3",

# npm run test

  391 passing (26s)
  5 pending
```

```shell
"glob": "^8.1.0",

# npm run test

  391 passing (26s)
  5 pending
```

```shell
"glob": "^9.3.5",

# npm run test

  385 passing (26s)
  5 pending
  6 failing
```

As you can see, tests do pass on version 8.

**Comment by ljharb** [comment]
@lloydjatkinson not on every version of node that tape supports.

**Comment by lloydjatkinson** [comment]
Are any of those old node versions not EOL?

**Comment by ljharb** [comment]
EOL status is irrelevant; dropping support for any node version is a breaking change, and eliminating a transitive deprecation warning is barely enough justification for a patch release, let alone a major.

**Pull request closed without merging**
